name: E2E tests
'on': pull_request
jobs:
  check:
    name: e2e_tests
    runs-on: ubuntu_20_64_core
    env:
      UPGRADEABLE_CONTRACTS:    "forward-calls set-code-hash"
      DELEGATOR_SUBCONTRACTS:   "accumulator adder subber"
      RUST_BACKTRACE:           full
    steps:

      - name: Checkout sources & submodules
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          submodules: recursive

      - name: Install toolchain
        id: toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rust-src
          override: true

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.2.0

      - name: Install `cargo-contract` `main`
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: --git https://github.com/paritytech/cargo-contract.git

      - name: Install cargo-dylint
        uses: baptiste0928/cargo-install@bf6758885262d0e6f61089a9d8c8790d3ac3368f # v1.3.0
        with:
          crate: cargo-dylint
          version: 1

      - name: Install dylint-link
        uses: baptiste0928/cargo-install@bf6758885262d0e6f61089a9d8c8790d3ac3368f # v1.3.0
        with:
          crate: dylint-link
          version: 1

      - name: Download and run latest `substrate-contracts-node` binary
        run: |
          curl -L -o substrate-contracts-node.zip 'https://gitlab.parity.io/parity/mirrors/substrate-contracts-node/-/jobs/artifacts/main/download?job=build-linux' && \
          unzip substrate-contracts-node.zip && \
          chmod +x artifacts/substrate-contracts-node-linux/substrate-contracts-node &&
          ./artifacts/substrate-contracts-node-linux/substrate-contracts-node -linfo,runtime::contracts=debug  2>&1 | tee /tmp/contracts-node.log &

      - name: Output versions
        run: |
          cargo -vV
          cargo contract --version

      - name: E2E tests
        run: |
          cd contracts/lottery
          cargo test --verbose --features e2e-tests

